import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout'
import { Head, Link, useForm } from '@inertiajs/react'

export default function Index({ auth, packs }) {
  const { data, setData, post, processing, errors } = useForm({
    period_start: '',
    period_end: '',
  })

  const submit = (e) => {
    e.preventDefault()
    post(route('compliance-export-packs.store'))
  }

  return (
    <AuthenticatedLayout user={auth.user} header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Compliance Export Packs</h2>}>
      <Head title="Compliance Export Packs" />
      <div className="py-6">
        <div className="mx-auto max-w-7xl space-y-4 sm:px-6 lg:px-8">
          <form onSubmit={submit} className="rounded-lg bg-white p-4 shadow">
            <div className="grid gap-3 sm:grid-cols-3">
              <div>
                <label className="text-sm font-medium text-gray-700">Period Start</label>
                <input type="date" className="mt-1 w-full rounded border-gray-300" value={data.period_start} onChange={(e) => setData('period_start', e.target.value)} />
                {errors.period_start && <p className="mt-1 text-xs text-red-600">{errors.period_start}</p>}
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700">Period End</label>
                <input type="date" className="mt-1 w-full rounded border-gray-300" value={data.period_end} onChange={(e) => setData('period_end', e.target.value)} />
                {errors.period_end && <p className="mt-1 text-xs text-red-600">{errors.period_end}</p>}
              </div>
              <div className="flex items-end">
                <button type="submit" disabled={processing} className="rounded bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">
                  Generate Pack
                </button>
              </div>
            </div>
          </form>

          <div className="overflow-hidden rounded-lg bg-white shadow">
            <table className="min-w-full divide-y divide-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left">Pack</th>
                  <th className="px-4 py-3 text-left">Period</th>
                  <th className="px-4 py-3 text-left">Counts</th>
                  <th className="px-4 py-3 text-left">Status</th>
                  <th className="px-4 py-3 text-left">Generated By</th>
                  <th className="px-4 py-3 text-left">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 bg-white">
                {packs.data.map((pack) => (
                  <tr key={pack.id}>
                    <td className="px-4 py-3 font-medium">{pack.pack_number}</td>
                    <td className="px-4 py-3">{pack.period_start} - {pack.period_end}</td>
                    <td className="px-4 py-3">Sensitive: {pack.record_counts?.audit_logs_sensitive || 0}, Retention: {pack.record_counts?.data_retention_executions || 0}, Workflow: {pack.record_counts?.workflow_decisions || 0}</td>
                    <td className="px-4 py-3">{pack.status}</td>
                    <td className="px-4 py-3">{pack.generator?.name || '-'}</td>
                    <td className="px-4 py-3">
                      <Link href={route('compliance-export-packs.show', pack.id)} className="text-indigo-600 hover:text-indigo-800">Detail</Link>
                    </td>
                  </tr>
                ))}
                {packs.data.length === 0 && (
                  <tr><td className="px-4 py-6 text-center text-gray-500" colSpan="6">Belum ada compliance export pack.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </AuthenticatedLayout>
  )
}
