import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout'
import { Head, Link } from '@inertiajs/react'

export default function Show({ auth, pack }) {
  return (
    <AuthenticatedLayout user={auth.user} header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Compliance Export Pack Detail</h2>}>
      <Head title={pack.pack_number} />
      <div className="py-6">
        <div className="mx-auto max-w-7xl space-y-4 sm:px-6 lg:px-8">
          <div className="rounded-lg bg-white p-6 shadow">
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <div><p className="text-xs text-gray-500">Pack</p><p className="font-medium">{pack.pack_number}</p></div>
              <div><p className="text-xs text-gray-500">Period</p><p className="font-medium">{pack.period_start} - {pack.period_end}</p></div>
              <div><p className="text-xs text-gray-500">Status</p><p className="font-medium">{pack.status}</p></div>
              <div><p className="text-xs text-gray-500">Generated By</p><p className="font-medium">{pack.generator?.name || '-'}</p></div>
            </div>
            <div className="mt-4 flex gap-2">
              <Link href={route('compliance-export-packs.download', pack.id)} className="rounded bg-green-600 px-3 py-2 text-sm font-semibold text-white">Download JSON</Link>
              <Link href={route('compliance-export-packs.index')} className="rounded border px-3 py-2 text-sm">Back</Link>
            </div>
          </div>

          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="text-lg font-semibold">Record Counts</h3>
            <div className="mt-3 grid gap-3 sm:grid-cols-3">
              <div className="rounded border p-3"><p className="text-xs text-gray-500">Sensitive Audit Logs</p><p className="text-xl font-semibold">{pack.record_counts?.audit_logs_sensitive || 0}</p></div>
              <div className="rounded border p-3"><p className="text-xs text-gray-500">Retention Executions</p><p className="text-xl font-semibold">{pack.record_counts?.data_retention_executions || 0}</p></div>
              <div className="rounded border p-3"><p className="text-xs text-gray-500">Workflow Decisions</p><p className="text-xl font-semibold">{pack.record_counts?.workflow_decisions || 0}</p></div>
            </div>
          </div>

          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="text-lg font-semibold">Metadata</h3>
            <pre className="mt-3 overflow-auto rounded bg-gray-900 p-4 text-xs text-gray-100">{JSON.stringify(pack.metadata, null, 2)}</pre>
          </div>
        </div>
      </div>
    </AuthenticatedLayout>
  )
}
